---
title: "Let's Get Physical: Inferring Latent Characteristics of NBA Games"
format: 
  html:
    toc: false
    number-sections: true
    css: ../styles.css
    embed-resources: true
editor: visual
author: "Michael Light"
---

# Project Motivation

## Background on the Role of Physicality in NBA Games

## Debate Surrounding Defense, Existing State of Research

## Project Scope and Significance

## Relevance and Novelty

## Broader Context

# Project Research Questions

## Primary Research Question

**Can an NBA game's latent physicality characteristic be inferred from play-by-play and Last Two Minute Report data?**

## Secondary Research Questions

**What is the effect of measurement error (referees incorrectly calling or not calling fouls) on players' true foul committing propensity?**

**What is the effect of measurement error (referees incorrectly calling or not calling fouls) on players' true foul drawing propensity?**

# Data Sources

## Primary Data Sources

### NBA Play-by-Play 

- **Type:** .parquet
- **Years:** 2023-2025
- **Size:** tk
- **Link:** 

### NBA Last Two Minute Reports

- **Type:** .parquet
- **Years:** 2023-2025
- **Size:** tk
- **Link:** 

# Causal Models

## Causal Model of In-Game Physicality

## Causal Model of Foul Committing Propensity

## Causal Model of Foul Drawing Propensity

# Generative Models

## Generative Model of In-Game Physicality

## Generative Model of Foul Committing Propensity

## Generative Model of Foul Drawing Propensity

# Statistical Models

## Statistical Model of In-Game Physicality

## Statistical Model of Foul Committing Propensity

## Statistical Model of Foul Drawing Propensity

# Prior Selection and Predictive Checks

## Prior Model of In-Game Physicality

### Less Constrained

### More Constrained

### Implicit

## Prior Model of Foul Committing Propensity

### Less Constrained

### More Constrained

### Implicit

## Prior Model of Foul Drawing Propensity

### Less Constrained

### More Constrained

### Implicit

# Model Validation

## Simulation Based Calibration

# Observed Sample Selection

## Observed Sample of In-Game Physicality

## Observed Sample of Foul Committing Propensity

## Observed Sample of Foul Drawing Propensity

# Model Fitting and Diagnostics

## Fitting Models to Observed Samples

## HMC Diagnostics

# Posterior Analysis

## Posterior Retrodictive Checks

## Posterior Residual Checks

# Counterfactual Analysis

# Conclusion
