---

---

```{r}
library(ggthemes)

# Definng a custom theme
theme_report <- function() {
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", color = "#333333"),
    plot.title = element_text(face = "bold", size = 16, color = "#2c3e50"),
    axis.title = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10)
  )
}

# Defining a color palette
report_colors <- c("#3498db", "#e74c3c", "#2ecc71", "#f39c12", "#9b59b6", 
                   "#1abc9c", "#d35400", "#34495e", "#7f8c8d", "#2980b9", "#8e44ad")
```

```{r}
library(tidyverse)
library(ggdag)
library(dagitty)
```

```{r}
l2m_dag <- dagitty('dag {
  Time -> League_Policy

  League_Policy -> Observed_Foul_Decision
  League_Policy -> True_Foul_Decision

  True_Foul_Decision -> Observed_Foul_Decision
  

}')


ggdag_status(l2m_dag) +
  theme_dag() +
  geom_dag_point(color = "lightblue", size = 20, alpha = 0.5) +
  geom_dag_text(color = "black", size = 4) +
  geom_dag_edges(edge_colour = "gray30", 
                 edge_width = 0.8) +
  theme_void() +
  theme(plot.background = element_rect(fill = "white", color = NA)) +
  scale_x_continuous(expand = expansion(mult = 0.2)) +
  scale_y_continuous(expand = expansion(mult = 0.2))  +
  ggtitle("Causal Model of Time's Effect on Foul Decisions")
```

